# Generated by Django 4.2.7 on 2023-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_type_rate_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
