# Generated by Django 4.2.7 on 2023-11-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_rate_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.SmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')]),
        ),
    ]
