version: "3.9"

services:
  backend:
    image: local
    build: .
    stdin_open: true
    tty: true
#    env_file: .env
    container_name: backend
    ports:
      - "8000:8000"
#      - "8001:8001" # dev port
    depends_on:
      - postgres
  #    volumes:
#      - "./:/project/code"

  postgres:
    image: postgres:15.6-alpine
    container_name: postgres
#    env_file: .env
#    ports:
#      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

#  nginx:
#    image: nginx
#    container_name: nginx
#    depends_on:
#      - backend
#    volumes:
#      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
#    ports:
#      - "80:80"

volumes:
  db_data: {}
