"""Added required tables

Revision ID: 33265b863308
Revises: 
Create Date: 2024-03-04 19:02:00.445893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33265b863308'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('event_ts', sa.BigInteger(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoom_webhook_events_event'), 'zoom_webhook_events', ['event'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoom_webhook_events_event'), table_name='zoom_webhook_events')
    op.drop_table('zoom_webhook_events')
    # ### end Alembic commands ###
